const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);
const tabs=['home','about','projects','activity','stack','now','contact'];
$$('.nav').forEach(b=>b.addEventListener('click',()=>{tabs.forEach(t=>$('#'+t)?.classList.remove('active'));$$('.nav').forEach(x=>x.classList.remove('active'));$('#'+b.dataset.tab).classList.add('active');b.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});if(b.dataset.tab==='projects')loadRepos();if(b.dataset.tab==='activity')loadActivity()}));
function clock(){$('#clock').textContent='TIME '+new Date().toLocaleTimeString('en-GB')}setInterval(clock,1000);clock();
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadRepos(){const box=$('#repos');if(box.dataset.loaded)return;try{const r=await fetch('https://api.github.com/users/matantan55/repos?sort=updated&per_page=12');const data=await r.json();box.innerHTML=data.map(x=>`<article class="repo"><h4>${esc(x.name)}</h4><p>${esc(x.description||'No description')}</p><span>${esc(x.language||'code')}</span> · <a href="${x.html_url}" target="_blank">open →</a></article>`).join('');box.dataset.loaded='1'}catch(e){box.innerHTML='<div class="loading">GitHub API unavailable.</div>'}}
async function loadActivity(){const boxes=[$('#feed'),$('#sidefeed')];try{const r=await fetch('https://api.github.com/users/matantan55/events/public?per_page=8');const data=await r.json();if(!Array.isArray(data))throw 0;const html=data.map(e=>{const repo=e.repo?.name||'GitHub';const type=e.type.replace('Event','');return `<div class="event"><b>${esc(type)}</b> · ${esc(repo)}<small>${new Date(e.created_at).toLocaleString()}</small></div>`}).join('');boxes[0].innerHTML=html||'<div class="loading">No recent public events.</div>';boxes[1].innerHTML=html?html.slice(0,1800):'<div class="loading">No recent events.</div>'}catch(e){boxes.forEach(x=>x.innerHTML='<div class="loading">Live feed unavailable.</div>')}}
$('#refresh').addEventListener('click',()=>{loadActivity();loadRepos()});loadActivity();
const input=$('#command'),out=$('#output');input.addEventListener('keydown',e=>{if(e.key!=='Enter')return;const c=input.value.trim().toLowerCase();input.value='';if(c==='clear'){out.textContent='';return}if(c==='help'||!c){out.textContent='about · projects · activity · stack · now · contact · clear · help';return}if(tabs.includes(c)){$(`[data-tab="${c}"]`).click();out.textContent='opening '+c+'...'}else out.textContent='command not found: '+c+' · type help'});
